# Generated by Django 4.2.7 on 2023-11-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('cor', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(max_length=60)),
                ('grau_escolaridade', models.CharField(max_length=80)),
                ('cep', models.CharField(max_length=10)),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=60)),
                ('cidade', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=60)),
                ('email_corporativo', models.CharField(max_length=200)),
                ('gerente', models.CharField(max_length=200)),
                ('departamento', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=200)),
                ('alergia', models.TextField()),
                ('tratamento_saude', models.TextField()),
                ('medicamento_continuo', models.TextField()),
                ('telefonepessoal1', models.CharField(max_length=30)),
                ('telefonepessoal2', models.CharField(max_length=30)),
                ('nome_emergencia1', models.CharField(max_length=200)),
                ('telefone_emergencia1', models.CharField(max_length=30)),
                ('grau_parentesco1', models.CharField(max_length=30)),
                ('nome_emergencia2', models.CharField(max_length=200)),
                ('telefone_emergencia2', models.CharField(max_length=30)),
                ('grau_parentesco2', models.CharField(max_length=30)),
                ('nome_dependente1', models.CharField(max_length=200)),
                ('cpf_dependente1', models.CharField(max_length=20)),
                ('nascimento_dependente1', models.CharField(max_length=30)),
                ('grau_parentesco_dependente1', models.CharField(max_length=30)),
                ('nome_dependente2', models.CharField(max_length=200)),
                ('cpf_dependente2', models.CharField(max_length=20)),
                ('nascimento_dependente2', models.CharField(max_length=30)),
                ('grau_parentesco_dependente2', models.CharField(max_length=30)),
                ('nome_dependente3', models.CharField(max_length=200)),
                ('cpf_dependente3', models.CharField(max_length=20)),
                ('nascimento_dependente3', models.CharField(max_length=30)),
                ('grau_parentesco_dependente3', models.CharField(max_length=30)),
                ('nome_dependente4', models.CharField(max_length=200)),
                ('cpf_dependente4', models.CharField(max_length=20)),
                ('nascimento_dependente4', models.CharField(max_length=30)),
                ('grau_parentesco_dependente4', models.CharField(max_length=30)),
            ],
        ),
    ]
