# Generated by Django 4.2.7 on 2023-11-21 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_att_cadastro', '0002_alter_funcionario_alergia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='id_login',
            field=models.ForeignKey(default=1, on_delete=models.SET('DELETADO'), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
