# Generated by Django 4.2.7 on 2023-11-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_att_cadastro', '0005_funcionario_modelo_trabalho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=30),
        ),
    ]
